version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: recipes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d recipes"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://app:pass@db:5432/recipes
      - REDIS_URL=redis://redis:6379
      - RL_BASE=http://rl-service:8000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      # Khi muốn dùng thêm RL-Service vào docker thì uncomment cái này
      rl-service:
        condition: service_started

  # ví dụ cho server RL-service sử dụng docker
  # (Nếu muốn dùng với docker, còn ko thì cứ định nghĩa trong env để chạy riêng là được rồi)
  rl-service:
    build: ./rl/sarsa # thư mục chứa Dockerfile của rl-service
    ports:
      - "8000:8000"
    restart: always

volumes:
  pgdata:
